//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesList.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamesEntities : DbContext
    {
        public GamesEntities()
            : base("name=GamesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Developers> Developers { get; set; }
        public DbSet<Disk_types> Disk_types { get; set; }
        public DbSet<Game_disks> Game_disks { get; set; }
        public DbSet<Game_Genres> Game_Genres { get; set; }
        public DbSet<Game_platforms> Game_platforms { get; set; }
        public DbSet<Game_protections> Game_protections { get; set; }
        public DbSet<Games> Games { get; set; }
        public DbSet<Genres> Genres { get; set; }
        public DbSet<Online_protections> Online_protections { get; set; }
        public DbSet<Platforms> Platforms { get; set; }
        public DbSet<Publishers> Publishers { get; set; }
        public DbSet<RF_Distributors> RF_Distributors { get; set; }
        public DbSet<Boxes> Boxes { get; set; }
        public DbSet<Editions> Editions { get; set; }
        public DbSet<GamesBoxes> GamesBoxes { get; set; }
        public DbSet<GamesEditions> GamesEditions { get; set; }
    }
}
