//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_disks
    {
        public decimal ID_Game_disk { get; set; }
        public Nullable<decimal> ID_Game { get; set; }
        public decimal ID_Disk_Type { get; set; }
        public Nullable<double> Kol_vo { get; set; }
    
        public virtual Disk_types Disk_types { get; set; }
        public virtual Games Games { get; set; }
    }
}
