//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamesEntities : DbContext
    {
        public GamesEntities()
            : base("name=GamesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boxes> Boxes { get; set; }
        public virtual DbSet<Developers> Developers { get; set; }
        public virtual DbSet<Disk_types> Disk_types { get; set; }
        public virtual DbSet<Editions> Editions { get; set; }
        public virtual DbSet<Game_disks> Game_disks { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Online_protections> Online_protections { get; set; }
        public virtual DbSet<Platforms> Platforms { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<RF_Distributors> RF_Distributors { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<GLDBVersion> GLDBVersion { get; set; }
    }
}
