//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLDBVersion
    {
        public decimal ID_V { get; set; }
        public Nullable<decimal> Version { get; set; }
    }
}
