//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Online_protections
    {
        public Online_protections()
        {
            this.Games = new HashSet<Games>();
        }
    
        public decimal ID_Protect { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Icon { get; set; }
    
        public virtual ICollection<Games> Games { get; set; }
    }
}
