//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesList.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disk_types
    {
        public Disk_types()
        {
            this.Game_disks = new HashSet<Game_disks>();
        }
    
        public decimal ID_Disk_Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Max_Size { get; set; }
    
        public virtual ICollection<Game_disks> Game_disks { get; set; }
    }
}
