//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesList.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public Games()
        {
            this.Game_disks = new HashSet<Game_disks>();
            this.Games1 = new HashSet<Games>();
            this.Online_protections = new HashSet<Online_protections>();
            this.Platforms = new HashSet<Platforms>();
            this.Genres = new HashSet<Genres>();
            this.Games11 = new HashSet<Games>();
        }
    
        public decimal ID_Game { get; set; }
        public string Name { get; set; }
        public decimal Status_complite { get; set; }
        public Nullable<double> Rate_person { get; set; }
        public Nullable<double> Rate_Igromania { get; set; }
        public byte[] Poster { get; set; }
        public Nullable<System.DateTime> Date_Release { get; set; }
        public Nullable<decimal> Localisation_Type { get; set; }
        public string Last_version { get; set; }
        public Nullable<decimal> Kol_updates { get; set; }
        public Nullable<bool> Game_Type { get; set; }
        public Nullable<decimal> ID_Publisher { get; set; }
        public Nullable<decimal> ID_Developer { get; set; }
        public Nullable<decimal> ID_RF_Distributor { get; set; }
        public string Original_Name { get; set; }
        public decimal ID_Edition { get; set; }
        public decimal ID_Box { get; set; }
        public Nullable<decimal> ID_Ser { get; set; }
        public string WhereStatus { get; set; }
        public byte[] WherePhoto { get; set; }
        public Nullable<decimal> ID_Content { get; set; }
        public Nullable<bool> TypeContent { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ID_Collect { get; set; }
    
        public virtual Boxes Boxes { get; set; }
        public virtual Developers Developers { get; set; }
        public virtual Editions Editions { get; set; }
        public virtual ICollection<Game_disks> Game_disks { get; set; }
        public virtual Publishers Publishers { get; set; }
        public virtual RF_Distributors RF_Distributors { get; set; }
        public virtual Series Series { get; set; }
        public virtual ICollection<Games> Games1 { get; set; }
        public virtual Games Games2 { get; set; }
        public virtual ICollection<Online_protections> Online_protections { get; set; }
        public virtual ICollection<Platforms> Platforms { get; set; }
        public virtual ICollection<Genres> Genres { get; set; }
        public virtual ICollection<Games> Games11 { get; set; }
        public virtual Games Games21 { get; set; }
    }
}
